BlogDjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('postagens.urls')),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

postagens/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.postagens_listar, name='postagens_listar'),
    url(r'^postagens/(?P<pk>[0-9]+)/$', views.postagens_detalhes, name='postagens_detalhes'),
    url(r'^postagens/criar/$', views.postagens_criar, name='postagens_criar'),
    url(r'^postagens/(?P<pk>[0-9]+)/editar/$', views.postagens_editar, name='postagens_editar'),
    url(r'^postagens/(?P<pk>[0-9]+)/excluir/$', views.postagens_excluir, name='postagens_excluir'),
    url(r'^postagens/rascunhos/$', views.postagens_rascunhos, name='postagens_rascunhos'),
    url(r'^postagens/(?P<pk>[0-9]+)/publicar/$', views.postagens_publicar, name='postagens_publicar'),
]

postagens/models.py
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.core.validators import validate_email
from django.db import models
from django.utils import timezone

from BlogDjango.settings import EMAIL_HOST_USER


class Postagem(models.Model):
    autor = models.ForeignKey('auth.User')
    titulo = models.CharField(max_length=200)
    descricao = models.TextField()
    conteudo = models.TextField()
    publicado = models.BooleanField(default=False)
    data_criacao = models.DateTimeField(default=timezone.now)
    data_publicacao = models.DateTimeField(blank=True, null=True)

    def publicar(self):
        self.publicado = True
        self.data_publicacao = timezone.now()
        self.save()

    def enviar(self, destinatario):
        try:
            mail = destinatario
            validate_email(mail)
        except ValidationError:
            mail = None

        if mail:
            send_mail(
                self.titulo,
                self.conteudo,
                EMAIL_HOST_USER,
                [mail],
                fail_silently=False,
            )
            return True

        return False

    def __str__(self):
        return self.titulo

postagens/forms.py
from django import forms
from .models import Postagem


class PostagemForm(forms.ModelForm):
    publicado = forms.BooleanField(required=False, initial=True)

    class Meta:
        model = Postagem
        fields = ('titulo', 'descricao', 'conteudo', 'publicado')

postagens/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Postagem
from .forms import PostagemForm


def postagens_listar(request):
    '''Listagem de todas as postagens'''
    postagens = Postagem.objects.filter(publicado=True)\
                                .order_by('-data_publicacao')

    # Exibição paginada, a cada três postagens
    paginator = Paginator(postagens, 3)
    page = request.GET.get('page')

    try:
        postagens = paginator.page(page)
    except PageNotAnInteger:
        postagens = paginator.page(1)
    except EmptyPage:
        postagens = paginator.page(paginator.num_pages)

    contexto = {'postagens': postagens}

    return render(request, 'postagens/postagens_listar.html', contexto)


@login_required
def postagens_rascunhos(request):
    '''Listagem de todas as postagens que ainda não foram publicadas'''
    postagens = Postagem.objects.filter(publicado=False) \
                                .order_by('-data_criacao')

    contexto = {'postagens': postagens}

    return render(request, 'postagens/postagens_rascunhos.html', contexto)


@login_required
def postagens_publicar(request, pk):
    '''Publicação de postagens rascunho'''
    postagem = get_object_or_404(Postagem, pk=pk)
    postagem.publicar()

    return redirect('postagens_detalhes', pk=pk)


def postagens_detalhes(request, pk):
    '''Listagem de uma postagem específica'''
    postagem = get_object_or_404(Postagem, pk=pk)

    contexto = {'postagem': postagem}

    if request.POST:
        if request.POST.get('email', None):

            if postagem.enviar(request.POST['email']):
                contexto['mail_result'] = 'Enviado'
            else:
                contexto['mail_result'] = 'E-mail inválido'
        else:
            contexto['mail_result'] = 'Preencha o email'

    return render(request, 'postagens/postagens_detalhes.html', contexto)


@login_required
def postagens_criar(request):
    '''Criação de uma nova postagem'''
    formulario = PostagemForm(request.POST or None)

    if request.POST:
        if formulario.is_valid():
            postagem = formulario.save(commit=False)
            postagem.autor = request.user
            postagem.save()

            if postagem.publicado:
                postagem.publicar()

            return redirect('postagens_detalhes', pk=postagem.pk)

    contexto = {'formulario': formulario}

    return render(request, 'postagens/postagens_editar.html', contexto)


@login_required
def postagens_editar(request, pk):
    '''Edição de uma postagem existente'''
    postagem = get_object_or_404(Postagem, pk=pk)

    if request.method == "POST":
        formulario = PostagemForm(request.POST, instance=postagem)
        if formulario.is_valid():
            postagem = formulario.save(commit=False)
            postagem.autor = request.user
            postagem.save()

            if postagem.publicado:
                postagem.publicar()
            else:
                postagem.data_publicacao = ""
                postagem.publicado = False

            return redirect('postagens_detalhes', pk=postagem.pk)
    else:
        formulario = PostagemForm(instance=postagem)

    contexto = {'formulario': formulario}

    return render(request, 'postagens/postagens_editar.html', contexto)


@login_required
def postagens_excluir(request, pk):
    '''Exclusão de uma postagem existente'''
    postagem = Postagem.objects.filter(pk=pk)
    postagem.delete()

    return redirect('postagens_listar')

templates/postagens/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Django</title>

    <!-- CSS de Personalização -->
    <link href="{% static 'dist/css/app.css' %}" rel="stylesheet">

    <!-- Fontes Personalizadas -->
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
</head>

<body>

    <!-- Navegação -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Alterador de navegação para dispositivos móveis -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Mudar navegação</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'postagens_listar' %}">#blogDjango</a>
            </div>

            <!-- Links de navegação -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        {% if user.is_authenticated %}
                        <a><span class="glyphicon glyphicon-user"></span> {{ request.user.first_name }} {{ request.user.last_name }}</a>
                    <li>
                    <a href="{% url 'logout' %}?next=/" title="Realizar logout">[ Sair ]</a>
                    </li>
                        {% else %}
                    <a href="{% url 'login' %}" title="Realizar login"><span class="glyphicon glyphicon-lock"></span> Login</a>
                    </li>
                        {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'postagens_listar' %}" title="Página inicial">
                            <span class="glyphicon glyphicon-home navbar-icones"></span>
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'postagens_rascunhos' %}">
                            <span class="glyphicon glyphicon-edit navbar-icones" title="Ver rascunhos de postagens"></span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'postagens_criar' %}">
                            <span class="glyphicon glyphicon-plus navbar-icones" title="Criar nova postagem"></span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Cabeçalho da Página e Conteúdo Principal -->
    {% block conteudo %}
    {% endblock %}

    <hr>

    <!-- Rodapé -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="http://github.com/marcomvidal/">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; #blogDjango 2017</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- JavaScript -->
    <script type="text/javascript" href="{% static 'dist/js/app.js' %}"></script>
</body>

</html>

templates/postagens/postagens_detalhes.html
{% extends 'postagens/base.html' %}
{% load staticfiles %}

{% block conteudo %}
<!-- Cabeçalho da Página -->
<header class="intro-header parallax">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1>{{ postagem.titulo }}</h1>
                    <div>
                        {% if user.is_authenticated %}
                        <a class="btn btn-default" href="{% url 'postagens_editar' pk=postagem.pk %}" title="Editar postagem">
                            <span class="glyphicon glyphicon-pencil btn-icones"></span>
                        </a>
                        <a class="btn btn-default" href="{% url 'postagens_excluir' pk=postagem.pk %}" title="Excluir postagem">
                            <span class="glyphicon glyphicon-remove btn-icones"></span>
                        </a>
                        {% endif %}
                        {% if not postagem.publicado %}
                        <a class="btn btn-default" href="{% url 'postagens_publicar' pk=postagem.pk %}" title="Publicar postagem">
                            <span class="glyphicon glyphicon-ok btn-icones"></span>
                        </a>
                        {% endif %}
                    </div>

                    <h2 class="subheading">{{ postagem.descricao | linebreaksbr }}</h2>

                    {% if postagem.publicado %}
                    <span class="meta">Publicado por <a href="#">{{ postagem.autor.first_name }} {{ postagem.autor.last_name }}</a> em {{ postagem.data_publicacao }}</span>
                    {% else %}
                    <span class="meta">Criado por <a href="#">{{ postagem.autor.first_name }} {{ postagem.autor.last_name }}</a> em {{ postagem.data_criacao }} (não publicado)</span>


                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Conteúdo da Postagem -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {{ postagem.conteudo | linebreaksbr }}

                {% if mail_result %}
                    <h2>{{ mail_result }}</h2>
                {% endif %}
            </div>
        </div>
    </div>


</article>
{% endblock conteudo %}

templates/postagens/postagens_editar.html
{% extends 'postagens/base.html' %}
{% load staticfiles %}

{% block conteudo %}
<!-- Cabeçalho da Página -->
<header class="intro-header parallax">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>#blogDjango</h1>
                    <hr class="small">
                    <span class="subheading">Dicas de desenvolvimento ágil de aplicações web</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Conteúdo Principal -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

            <div class="post-preview">
                <h2 class="post-title">Criar ou editar postagem</h2>
                <form method="POST">
                    {% csrf_token %}

                    <div class="form-group {% if formulario.titulo.errors %}has-error{% endif %}">
                        <label class="control-label">Título</label>
                        <input class="form-control" type="text" name="titulo" placeholder="Sobre o quê se trata esta postagem?" value="{{ formulario.titulo.value|default:'' }}">
                        <p class="help-block">{{ formulario.titulo.errors|striptags }}</p>
                    </div>

                    <div class="form-group {% if formulario.descricao.errors %}has-error{% endif %}">
                        <label class="control-label">Descrição</label>
                        <input class="form-control" type="text" name="descricao" placeholder="Descreva brevemente sobre do que se trata esta postagem" value="{{ formulario.descricao.value|default:'' }}">
                        <p class="help-block">{{ formulario.descricao.errors|striptags }}</p>
                    </div>

                    <div class="form-group {% if formulario.conteudo.errors %}has-error{% endif %}">
                        <label class="control-label">Conteúdo</label>
                        <textarea class="form-control" name="conteudo" placeholder="Digite aqui o texto que aparecerá no corpo da sua postagem" rows="10">{{ formulario.conteudo.value|default:'' }}</textarea>
                        <p class="help-block">{{ formulario.conteudo.errors|striptags }}</p>
                    </div>

                    <div class="form-group">
                        {{ formulario.publicado }}
                        <label class="control-label" for="id_publicado">Deseja publicar esta postagem agora?</label>
                    </div>
                    <hr>
                    <button class="btn btn-primary" type="submit">Salvar</button>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock conteudo %}

templates/postagens/postagens_listar.html
{% extends 'postagens/base.html' %}
{% load staticfiles %}

{% block conteudo %}
<!-- Cabeçalho da Página -->
<header class="intro-header parallax">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>#blogDjango</h1>
                    <hr class="small">
                    <span class="subheading">Dicas de desenvolvimento ágil de aplicações web</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Conteúdo Principal -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            {% for postagem in postagens %}
            <div class="post-preview">
                <a href="{% url 'postagens_detalhes' pk=postagem.pk %}">
                    <h2 class="post-title">
                        {{ postagem.titulo }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ postagem.descricao | linebreaksbr }}
                    </h3>
                </a>
                <p class="post-meta">Publicado por <a href="#">{{ postagem.autor.first_name }} {{ postagem.autor.last_name }}</a> em {{ postagem.data_publicacao }}</p>
            </div>
            <hr>
            {% endfor %}

            <!-- Paginador -->
            <ul class="pager">
                <li class="previous">
                    {% if postagens.has_previous %}
                        <a href="?page={{ postagens.previous_page_number }}">&larr; Anteriores</a>
                    {% endif %}
                </li>
                <li class="next">
                    {% if postagens.has_next %}
                        <a href="?page={{ postagens.next_page_number }}">Próximas &rarr;</a>
                    {% endif %}
                </li>
            </ul>

        </div>
    </div>
</div>
{% endblock conteudo %}

templates/postagens/postagens_rascunhos.html
{% extends 'postagens/base.html' %}
{% load staticfiles %}

{% block conteudo %}
<!-- Cabeçalho da Página -->
<header class="intro-header parallax">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>#blogDjango</h1>
                    <hr class="small">
                    <span class="subheading">Dicas de desenvolvimento ágil de aplicações web</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Conteúdo Principal -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            {% for postagem in postagens %}
            <div class="post-preview">
                <a href="{% url 'postagens_detalhes' pk=postagem.pk %}">
                    <h2 class="post-title">
                        {{ postagem.titulo }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ postagem.descricao | linebreaksbr }}
                    </h3>
                </a>
            </div>
            <hr>
            {% endfor %}

            <!-- Paginador -->
            <ul class="pager">
                <li class="previous">
                    {% if postagens.has_previous %}
                        <a href="?page={{ postagens.previous_page_number }}">&larr; Anteriores</a>
                    {% endif %}
                </li>
                <li class="next">
                    {% if postagens.has_next %}
                        <a href="?page={{ postagens.next_page_number }}">Próximas &rarr;</a>
                    {% endif %}
                </li>
            </ul>

        </div>
    </div>
</div>
{% endblock conteudo %}